wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1639779361
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 13
      - 16
      4: 3.8.8
      5: 0.12.9
      8:
      - 5
agents:
  desc: null
  value: 16
batch_size:
  desc: null
  value: 4
bottleneck_bits:
  desc: null
  value: 128
bottleneck_noise:
  desc: null
  value: 0.1
clip_grad_norm:
  desc: null
  value: 1.0
compress_steps:
  desc: null
  value: 5
device:
  desc: null
  value: cuda
done_on_last_rollout_step:
  desc: null
  value: true
dropout:
  desc: null
  value: 0.15
env_name:
  desc: null
  value: Freeway
epochs:
  desc: null
  value: 15
experiment_name:
  desc: null
  value: 17-12-21-14:15:54
filter_double_steps:
  desc: null
  value: 3
frame_shape:
  desc: null
  value:
  - 3
  - 105
  - 80
hidden_layers:
  desc: null
  value: 2
hidden_size:
  desc: null
  value: 96
input_noise:
  desc: null
  value: 0.05
latent_rnn_max_sampling:
  desc: null
  value: 0.5
latent_state_size:
  desc: null
  value: 128
latent_use_max_probability:
  desc: null
  value: 0.8
load_models:
  desc: null
  value: false
noop_max:
  desc: null
  value: 8
ppo_gamma:
  desc: null
  value: 0.99
ppo_lr:
  desc: null
  value: 0.0001
recurrent_state_size:
  desc: null
  value: 64
render_evaluation:
  desc: null
  value: false
render_training:
  desc: null
  value: false
residual_dropout:
  desc: null
  value: 0.5
rollout_length:
  desc: null
  value: 50
save_models:
  desc: null
  value: false
scheduled_sampling_decay_steps:
  desc: null
  value: 22250
simulation_flip_first_random_for_beginning:
  desc: null
  value: true
stack_internal_states:
  desc: null
  value: true
stacking:
  desc: null
  value: 4
target_loss_clipping:
  desc: null
  value: 0.03
trust_region_beta:
  desc: null
  value: 1.0
use_ppo_lr_decay:
  desc: null
  value: false
use_stochastic_model:
  desc: null
  value: true
use_wandb:
  desc: null
  value: true
